Text save
Ha-limLee/Sticky-Notes-Improved pull request #19
Opened 2021-05-20 19:13 UTC by Ha-limLee

closes #18

2021-05-21 03:26 UTC, ShapeLayer reviewed
Refer to https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

2021-05-24 15:27 UTC, ShapeLayer reviewed
`app/renderer/preloads/index,js` (line 19)  
api의 test: () =>{}가 무엇을 위해 작성되었나요?  
ipcRender.on()은 이벤트를 한번 바인딩 하고 끝일텐데, 이걸 여기에서 사용한 이유를 모르겠습니다.

2021-05-24 16:15 UTC, ShapeLayer requested changes
이해가 힘든 코드 수정 사항도 있고, 조금 더 개선할 수 있을 것 같은 코드가 있을 것 같아 일단 각 부분에 관련 내용 달아두었습니다. 확인 부탁드립니다.

2021-05-24 16:15 UTC, ShapeLayer commented on app/renderer/noteWindow.js
> +    const testHandler = () => {
`testHandler`는 사용하지 않는 핸들러입니다.  
또한 이 핸들러에서 사용하는 `this.test()`가 정확히 존재하는지도 확인하지 못했습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> -require('./app/main/ipcMain')
`./app/main/ipcMain`으로 ipcMain 처리를 분리시켰었는데, 다시 통합하셨습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> +// Global variables
새로 추가한 전역 변수의 사용처가 확실하게 확인되지 않았습니다.  
특히 `noteIDCache`와 `noteTextCache`는 전역 변수로 처리할만한 것들인지 잘 모르겠습니다.  
되도록 캡슐화된 코드를 지향해주셨으면 좋겠습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on app/renderer/noteWindow.js
> +      id: '' // It will be used to save and load data
`componentDidMount () {}`에서 이 state는 `window.api.getNoteId()`를 통해 main 프로세스의 전역 변수인 `noteIdCache`를 가져왔습니다. 하지만 `noteIdCache`가 현재 noteWindow의 ID와 일치함을 담보할 수 있는지는 잘 모르겠습니다.

`noteIdCache`는 하나지만, noteWindow는 한 순간에 여러 개 열릴 수 있습니다. 이는 노트 윈도우의 ID가 현재 ID와 무조건 일치할 수는 없을 수 있음을 시사한다고 생각합니다. `this.props.id`와 비교하여 이 방식이 갖는 이점이 무엇인지 잘 모르겠습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on app/main/ipcMain.js
> +const { ipcMain, app } = require('electron')
`app`이 파일 내에서 사용되지 않았습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on app/main/ipcMain.js
> +const { ipcMain, app } = require('electron')
ipcMain 파일이 현재 제대로 사용되고 있는 것 같지 않습니다. 사용하지 않는 파일은 제거하는 편이 확인하기 편할 것 같습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> +ipcMain.on('getNoteId', (event) => {
전역 변수로 지정한 `noteIdCache`를 컴포넌트에게 전달하는 이유를 잘 모르겠습니다. `app/renderer/noteWindow`에서 한번 달아놓았던 리뷰 내용을 참조해주세요.

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> +ipcMain.on('sendNoteText', (event, id, text) => {
디버그용으로 작성한 코드인지 확인 부탁드립니다.

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> +      mainWindow.reload()
단일 창을 사용하는 앱이 아니라 여러개의 윈도우를 생성하는 앱이기 때문에, 노트 윈도우를 닫을 때만 내용을 처음부터 다시 불러오는건 특정 노트를 수정하는 동안 메인 윈도우에 수정 내용이 반영되지 않습니다.

또 페이지 전체를 다시 불러오면 메인 페이지 전체가 깜빡이게 되는데, 혹시 mainWindow의 프론트 단(컴포넌트 내부에서 정의)에서 setInterval을 사용하여 수정 사항을 일부만 주기적으로 불러오는 방법은 어떨까요? 계속해서 관련 기능을 호출해야하지만, 호출에 소모되는 리소스는 많이 적을 것 같습니다.

```
* 리액트는 문서 내용을 수정할 때 문서 전체나 컴포넌트 전체를 수정하는 것이 아니라 수정된 내용 일부만 수정하는 방식을 채택하고 있습니다.
```

2021-05-24 16:15 UTC, ShapeLayer commented on main.js
> +      mainWindow.reload()
전역 변수 `noteWindow`는 이 부분에서밖에 사용하고 있지 않은 것 같습니다. 위 방향으로 처리를 변경하면 전역 변수라는 부담을 덜 수 있을 것 같습니다.

2021-05-24 16:15 UTC, ShapeLayer commented on app/renderer/components/lobby/NoteFrame/index.js
> +    this.testMessage = ''
🤔

2021-05-24 16:15 UTC, ShapeLayer commented on app/renderer/components/lobby/NoteIndex/index.js
> +    if (fromNoteWindow.id) {
아래 코드가 어떤 역할을 하는지 설명 부탁드립니다.

2021-05-25 03:32 UTC, Ha-limLee commented on main.js
> -require('./app/main/ipcMain')
제가 확인한 바로는 main.js와 ipcMain.js가 다른 프로세스에서 돌아갔습니다.
main.js에서 `mainWindow`를 만들고 ipcMain.js에서 `noteWindow`를 만들면 두 window가 상호작용 하는 게 너무 복잡해서 통합했습니다.

더 좋은 방법이 있다면 알려주세요.

2021-05-25 03:34 UTC, Ha-limLee commented on main.js
> +// Global variables
전역이 아니라 main.js에서만 사용되는 변수들입니다. 주석을 수정하겠습니다.

2021-05-27 00:21 UTC, Ha-limLee commented
구조를 크게 바꿨습니다. 

- localStorage에 noteId와 text를 저장합니다.
- noteFrame을 클릭하면 해당 noteFrame의 noteId가 main.js에 전달됩니다.
- main.js에서 noteWindow를 생성하고 noteWindow의 renderer는 noteId를 요청합니다.
  Set 자료형을 사용하기 때문에 noteFrame과 noteWindow의 id는 반드시 같습니다.
- noteWindow의 renderer는 text를 localStorage에서 가져옵니다.

2021-05-28 01:38 UTC, ShapeLayer approved these changes

2021-05-30 07:56 UTC, ShapeLayer commented
> ShapeLayer approved these changes 2 days ago

변경 사항 확인했습니다. 혹시 확인하지 못하신 것 같아 다시 말씀드려요

2021-05-30 13:45 UTC, merged